<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="merge"
    nsURI="merge" nsPrefix="merge">
  <eClassifiers xsi:type="ecore:EDataType" name="AType" instanceClassName="a.type"/>
  <eSubpackages name="adding" nsURI="adding" nsPrefix="adding">
    <eSubpackages name="add1" nsURI="add1" nsPrefix="add1"/>
    <eSubpackages name="add2" nsURI="add2" nsPrefix="add2"/>
    <eSubpackages name="add3" nsURI="add3" nsPrefix="add3"/>
  </eSubpackages>
  <eSubpackages name="del1" nsURI="del1" nsPrefix="del1">
    <eClassifiers xsi:type="ecore:EClass" name="DeletedElement" instanceClassName="instance.type">
      <eOperations name="operation" unique="false" upperBound="2" eType="#//AType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="glubber" unique="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          defaultValueLiteral="42" unsettable="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="del2" nsURI="del2" nsPrefix="del2">
    <eClassifiers xsi:type="ecore:EClass" name="DeletedElement" instanceClassName="instance.type">
      <eOperations name="operation" unique="false" upperBound="2" eType="#//AType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="glubber" unique="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          defaultValueLiteral="42" unsettable="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="del3" nsURI="del3" nsPrefix="del3">
    <eClassifiers xsi:type="ecore:EClass" name="DeletedElement" instanceClassName="instance.type">
      <eOperations name="operation" unique="false" upperBound="2" eType="#//AType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="glubber" unique="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          defaultValueLiteral="42" unsettable="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="oldPlace" nsURI="oldPlace" nsPrefix="oldPlace">
    <eAnnotations source="aSource">
      <details key="just" value="nothing at all 1"/>
    </eAnnotations>
    <eAnnotations source="bSource">
      <details key="just" value="nothing at all 2"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="blue" instanceClassName="lang.color"/>
    <eClassifiers xsi:type="ecore:EClass" name="red" instanceClassName="lang.color"/>
    <eClassifiers xsi:type="ecore:EClass" name="green" instanceClassName="lang.color"/>
  </eSubpackages>
  <eSubpackages name="newPlace" nsURI="newPlace" nsPrefix="newPlace"/>
</ecore:EPackage>
