<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoretest"
    nsURI="ecoretest" nsPrefix="ecoretest">
  <eClassifiers xsi:type="ecore:EClass" name="SuperType1" abstract="true">
    <eOperations name="operation" ordered="false" lowerBound="5" upperBound="6" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="something" ordered="false" lowerBound="1" eType="#//SuperType2"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperType2"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubType1" eSuperTypes="#//SuperType1">
    <eOperations name="moveMe" unique="false" lowerBound="1" eType="#//SubType1">
      <eParameters name="X" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubType2" eSuperTypes="#//SuperType1 #//SuperType2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType1" eType="#//X"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType2" defaultValueLiteral="blub"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType3" eType="#//X"
        defaultValueLiteral="bla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="X" instanceTypeName="X"/>
</ecore:EPackage>
