/*
 * generated by Xtext
 */
package org.eclipse.emf.compare.epatch.dsl.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://wiki.eclipse.org/Xtext/Documentation#Scoping
 * on how and when to use it 
 *
 */
public class EpatchScopeProvider extends AbstractDeclarativeScopeProvider {

}
