<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="applied"
    nsURI="applied" nsPrefix="applied">
  <eSubpackages name="change" nsURI="change" nsPrefix="change">
    <eClassifiers xsi:type="ecore:EClass" name="ChangeMyInstanceTypeName">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ExternalReferenceToLocal"
          lowerBound="2" upperBound="2" eType="#//change/ChangeMyInstanceTypeName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeMyReference">
      <eOperations name="clearMyType"/>
      <eOperations name="setMyType" ordered="false" eType="#//change/ChangeMyInstanceTypeName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ChangeMeToLocal" eType="#//change/ChangeMyReference"/>
    </eClassifiers>
    <eSubpackages name="old" nsURI="old" nsPrefix="old"/>
    <eSubpackages name="new" nsURI="new" nsPrefix="new">
      <eClassifiers xsi:type="ecore:EClass" name="moveMe">
        <eOperations name="something" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="moveMeToo">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nestedMove" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
            derived="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="remove" nsURI="remove" nsPrefix="remove">
    <eClassifiers xsi:type="ecore:EClass" name="existing"/>
  </eSubpackages>
  <eSubpackages name="add" nsURI="add" nsPrefix="add">
    <eClassifiers xsi:type="ecore:EClass" name="staticThing" eSuperTypes="#//add/addedPack/aClass"/>
    <eClassifiers xsi:type="ecore:EDataType" name="addedDatatype" instanceTypeName="blub"/>
    <eSubpackages name="addedPack" nsURI="addedPack" nsPrefix="addedPack">
      <eClassifiers xsi:type="ecore:EClass" name="aClass" instanceTypeName="asdf"
          abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="aRef" eType="#//add/staticThing"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Thingie"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
