<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="applied"
    nsURI="applied" nsPrefix="applied">
  <eSubpackages name="change" nsURI="change" nsPrefix="change">
    <eClassifiers xsi:type="ecore:EClass" name="ChangeMyInstanceTypeName" instanceTypeName="ClearMeToNull">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ExternalReferenceToLocal"
          lowerBound="2" upperBound="2" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeMyReference">
      <eOperations name="clearMyType" eType="#//change/ChangeMyReference"/>
      <eOperations name="setMyType" ordered="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ChangeMeToLocal" eType="#//change/ChangeMyInstanceTypeName"/>
    </eClassifiers>
    <eSubpackages name="old" nsURI="old" nsPrefix="old">
      <eClassifiers xsi:type="ecore:EClass" name="moveMe">
        <eOperations name="something" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nestedMove" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
            derived="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="moveMeToo"/>
    </eSubpackages>
    <eSubpackages name="new" nsURI="new" nsPrefix="new"/>
  </eSubpackages>
  <eSubpackages name="remove" nsURI="remove" nsPrefix="remove">
    <eClassifiers xsi:type="ecore:EClass" name="existing" eSuperTypes="#//remove/complexThing/blub">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delMe" ordered="false"
          eType="#//remove/complexThing/anyType"/>
    </eClassifiers>
    <eSubpackages name="complexThing" nsURI="complexThing" nsPrefix="complexThing">
      <eClassifiers xsi:type="ecore:EClass" name="bla" eSuperTypes="#//remove/existing">
        <eOperations name="bla" ordered="false" upperBound="4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
          <eParameters name="a" unique="false" eType="#//remove/complexThing/anyType">
            <eAnnotations source="sss">
              <details key="key" value="value"/>
            </eAnnotations>
          </eParameters>
          <eParameters name="b" unique="false" eType="#//remove/complexThing/anyType"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="blub" eType="#//remove/complexThing/anyType">
          <eAnnotations source="source"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="anyType" instanceClassName="java.nothing"/>
      <eClassifiers xsi:type="ecore:EClass" name="blub" abstract="true" interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="toExisting" eType="#//remove/existing"
            changeable="false" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" upperBound="-1"
            eType="#//remove/complexThing/bla" transient="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="add" nsURI="add" nsPrefix="add">
    <eClassifiers xsi:type="ecore:EClass" name="staticThing"/>
  </eSubpackages>
</ecore:EPackage>
