<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml2diff" nsURI="http://www.eclipse.org/emf/compare/diff/uml2/2.0"
    nsPrefix="uml2diff">
  <eClassifiers xsi:type="ecore:EClass" name="UMLAssociationChange" eSuperTypes="#//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLDependencyChange" eSuperTypes="#//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLInterfaceRealizationChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLSubstitutionChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLExtendChange" eSuperTypes="#//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Extend"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLGeneralizationSetChange" eSuperTypes="#//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizationSet" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLExecutionSpecificationChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLDestructionEventChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLIntervalConstraintChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLMessageChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLStereotypePropertyChange" eSuperTypes="#//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLStereotypeApplicationChange" eSuperTypes="platform:/plugin/org.eclipse.emf.compare/model/compare.ecore#//ReferenceChange #//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLStereotypeReferenceChange" eSuperTypes="#//UMLExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLProfileApplicationChange" eSuperTypes="platform:/plugin/org.eclipse.emf.compare/model/compare.ecore#//ReferenceChange #//UMLExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLExtension" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.compare/model/compare.ecore#//Diff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="discriminant" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
