<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="external"
    nsURI="externalURI" nsPrefix="compare.tests.external">
  <eClassifiers xsi:type="ecore:EClass" name="StringHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Holder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringHolder" eType="#//StringHolder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoncontainmentHolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringHolder" eType="#//StringHolder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HolderHolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="holder" eType="#//NoncontainmentHolder"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
