<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nodes"
    nsURI="namespaceURI" nsPrefix="compare.tests">
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="noncontainmentHolder" eType="ecore:EClass external.ecore#//StringHolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentHolder" eType="ecore:EClass external.ecore#//StringHolder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holder" eType="ecore:EClass external.ecore#//Holder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonEMF" eType="#//NonEMFStringHolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noncontainmentNoncontainmentHolder"
        eType="ecore:EClass external.ecore#//NoncontainmentHolder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="#//UUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UUID" instanceClassName="java.util.UUID"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NonEMFStringHolder" instanceClassName="org.eclipse.emf.compare.tests.nonemf.NonEMFStringHolder"/>
</ecore:EPackage>
