<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root"
    nsURI="none">
  <eClassifiers xsi:type="ecore:EClass" name="Class1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class1Attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class1Clone">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class1Attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class1Altered" interface="true">
    <eOperations name="class1Operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class1Attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="public"/>
    <eLiterals name="package" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="private" value="3"/>
    <eLiterals name="anonynner" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass"/>
  <eSubpackages name="Package1"/>
  <eSubpackages name="structureSimilarityTests">
    <eSubpackages name="similar">
      <eClassifiers xsi:type="ecore:EClass" name="AClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="aReference" eType="#//structureSimilarityTests/similar/AnotherClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SecondClass"/>
      <eClassifiers xsi:type="ecore:EClass" name="AnotherClass" eSuperTypes="#//structureSimilarityTests/similar/AClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="itsAttrIsntTheSame"
            eType="#//structureSimilarityTests/similar/AndADataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="AndADataType" instanceClassName="java.lang.Object"/>
      <eSubpackages name="ThisIsToAddSomethingToTheSurroundings"/>
    </eSubpackages>
    <eSubpackages name="similar">
      <eClassifiers xsi:type="ecore:EClass" name="AClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="aReference" eType="#//structureSimilarityTests/similar.1/AnotherClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SecondClass"/>
      <eClassifiers xsi:type="ecore:EClass" name="AnotherClass" eSuperTypes="#//structureSimilarityTests/similar.1/AClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="itsAttrIsntTheSame"
            eType="#//structureSimilarityTests/similar.1/AndADataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="AndADataType" instanceClassName="java.lang.Object"/>
      <eSubpackages name="ThisIsToAddSomethingToTheSurroundings"/>
    </eSubpackages>
    <eSubpackages name="noPairInCommon">
      <eClassifiers xsi:type="ecore:EClass" name="Library">
        <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
            eType="#//structureSimilarityTests/noPairInCommon/Book"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
            eType="#//structureSimilarityTests/noPairInCommon/Author"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Book">
        <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//structureSimilarityTests/noPairInCommon/Author"
            eOpposite="#//structureSimilarityTests/noPairInCommon/Author/books"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="#//structureSimilarityTests/noPairInCommon/LString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Author">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//structureSimilarityTests/noPairInCommon/LString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
            eType="#//structureSimilarityTests/noPairInCommon/Book" eOpposite="#//structureSimilarityTests/noPairInCommon/Book/author"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="LString" instanceClassName="java.lang.String">
        <eAnnotations source="This will add to the difference"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
