<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="performance"
    nsURI="performance" nsPrefix="performance">
  <eClassifiers xsi:type="ecore:EClass" name="SuperType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OldReferenceTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewReferenceTarget"/>
  <eSubpackages name="oldPlace" nsURI="oldPlace" nsPrefix="oldPlace"/>
  <eSubpackages name="newPlace" nsURI="newPlace" nsPrefix="newPlace">
    <eClassifiers xsi:type="ecore:EClass" name="Class000" eSuperTypes="#//SuperType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
          eType="#//NewReferenceTarget"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class001" eSuperTypes="#//SuperType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
          eType="#//NewReferenceTarget"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
