/*
 * generated by Xtext
 */
package org.eclipse.emf.compare.epatch.dsl;

import org.eclipse.xtext.ui.common.service.DefaultUIModule;

/**
 * Manual modifications go to {org.eclipse.emf.compare.epatch.dsl.EpatchUiModule}
 */
public abstract class AbstractEpatchUiModule extends DefaultUIModule {

	public Class<? extends org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.ITokenColorer> bindITokenColorer() {
		return org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.CommonAntlrTokenColorer.class;
	}

	public Class<? extends org.eclipse.jface.text.rules.ITokenScanner> bindITokenScanner() {
		return org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.AntlrTokenScanner.class;
	}

	public Class<? extends org.eclipse.xtext.ui.common.editor.contentassist.IProposalProvider> bindIProposalProvider() {
		return org.eclipse.emf.compare.epatch.dsl.EpatchProposals.class;
	}
}
