/*
* generated by Xtext
*/
package org.eclipse.emf.compare.epatch.dsl.outline;

import org.eclipse.xtext.ui.common.editor.outline.impl.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class EpatchTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
