<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoretest"
    nsURI="ecoretest" nsPrefix="ecoretest">
  <eAnnotations source="http://ecore/Gendocdingenskirchen" references="http://www.eclipse.org/emf/2002/Ecore#//EByteObject">
    <details key="body" value="true / false"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="Y" instanceTypeName="blubberdiglub"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperType2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reff" upperBound="55" eType="#//SubType1"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubType1" eSuperTypes="#//SuperType1 #//SuperType2"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubType2" eSuperTypes="#//SuperType1">
    <eOperations name="moveMe" unique="false" lowerBound="1" eType="#//SubType1">
      <eParameters name="X" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType3" defaultValueLiteral="blub"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType2" eType="#//Y"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superType1" eType="#//Y"
        defaultValueLiteral="bla"/>
  </eClassifiers>
</ecore:EPackage>
