<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mpatch"
    nsURI="http://www.eclipse.org/emf/compare/mpatch/1.0" nsPrefix="mpatch">
  <eClassifiers xsi:type="ecore:EClass" name="MPatchModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changes" upperBound="-1"
        eType="#//IndepChange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfdiff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepChange" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingElement" eType="#//IElementReference"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The corresponding element is the element that is actually changed. &lt;br>&#xD;&#xA;In case of an attribute- or reference-change, it is the owner of the attribute / reference.&lt;br>&#xD;&#xA;In case of an add- or remove-element-change, it is the parent of the added / removed element.&lt;br>&#xD;&#xA;In case of a move-element-change, it is the moved element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeKind" eType="#//ChangeKind"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Derived from the concrete type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeType" eType="#//ChangeType"
        changeable="false" volatile="true" transient="true" defaultValueLiteral=""
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Derived from the concrete type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
        eType="#//IndepChange" eOpposite="#//IndepChange/dependants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependants" upperBound="-1"
        eType="#//IndepChange" eOpposite="#//IndepChange/dependsOn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultingElement" eType="#//IElementReference"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The corresponding element is the element that is actually changed. &lt;br>&#xD;&#xA;In case of an attribute- or reference-change, it is the owner of the attribute / reference.&lt;br>&#xD;&#xA;In case of an add- or remove-element-change, it is the parent of the added / removed element.&lt;br>&#xD;&#xA;In case of a move-element-change, it is the moved element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeGroup" eSuperTypes="#//IndepChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subChanges" upperBound="-1"
        eType="#//IndepChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepElementChange" abstract="true"
      eSuperTypes="#//IndepChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddRemElementChange" abstract="true"
      eSuperTypes="#//IndepElementChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModel" lowerBound="1"
        eType="#//IModelDescriptor" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sub-model descriptor contains an abstract description of a sub-model, including contained elements as well as outgoing references.&#xD;&#xA;IModelDescriptor.requiredReferences returns a list of all outgoing references."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containment" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The structural feature of the correspondingElement which contains the added or removed element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModelReference" lowerBound="1"
        eType="#//IElementReference" changeable="false" volatile="true" transient="true"
        derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddElementChange" eSuperTypes="#//IndepAddRemElementChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepRemoveElementChange" eSuperTypes="#//IndepAddRemElementChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAttributeChange" abstract="true"
      eSuperTypes="#//IndepChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedAttribute" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddRemAttributeChange" abstract="true"
      eSuperTypes="#//IndepAttributeChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepMoveElementChange" eSuperTypes="#//IndepElementChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldContainment" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newContainment" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldParent" lowerBound="1"
        eType="#//IElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newParent" lowerBound="1"
        eType="#//IElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddAttributeChange" eSuperTypes="#//IndepAddRemAttributeChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepRemoveAttributeChange" eSuperTypes="#//IndepAddRemAttributeChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepUpdateAttributeChange" eSuperTypes="#//IndepAttributeChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepReferenceChange" abstract="true"
      eSuperTypes="#//IndepChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddRemReferenceChange" abstract="true"
      eSuperTypes="#//IndepReferenceChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedReference" lowerBound="1"
        eType="#//IElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndepAddReferenceChange" eSuperTypes="#//IndepAddRemReferenceChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepRemoveReferenceChange" eSuperTypes="#//IndepAddRemReferenceChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndepUpdateReferenceChange" eSuperTypes="#//IndepReferenceChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldReference" eType="#//IElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newReference" eType="#//IElementReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IElementReference" abstract="true" interface="true">
    <eOperations name="resolve" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;code>lowerBound&lt;/code> and &lt;code>upperBound&lt;/code> define the number of allowed resolved elements here."/>
      </eAnnotations>
      <eParameters name="model" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="resolvesEqual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//IElementReference"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        changeable="false" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IModelDescriptor" abstract="true" interface="true">
    <eOperations name="applyCrossReferences" upperBound="-1" eType="#//IElementReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This restores all cross references of the object given in the parameter.&#xD;&#xA;The parameter must be created by &lt;b>applyStructure&lt;/b> before!&#xD;&#xA;&#xD;&#xA;It returns all references which were &lt;b>not&lt;/b> successfully restored; this is a subset of &lt;b>crossReferences&lt;/b>."/>
      </eAnnotations>
      <eParameters name="createdObject" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="resolvedCrossReferences" upperBound="-1" eType="#//ElementReferenceToEObjectMap"/>
    </eOperations>
    <eOperations name="applyStructure" upperBound="-1" eType="#//EObjectToIModelDescriptorMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This applies the described element to a given modelElement using the given containment.&#xD;&#xA;I.e. all model-descriptors restore their structure, that is the model elements and their attributes.&#xD;&#xA;&#xD;&#xA;Please note that the references must be restored separately using &lt;b>applyCrossReferences()&lt;/b>!&#xD;&#xA;The reason for the separation is that the restoring of cross references requires all model elements to exist before.&#xD;&#xA;&#xD;&#xA;The result is a map from all model elements within the containment tree of the created element to their respective model descriptors."/>
      </eAnnotations>
      <eParameters name="modelElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="containment" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    </eOperations>
    <eOperations name="describesEqual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is a semantical equals-check; if the arguments and the object itself describe the same model elements, this operation must return true."/>
      </eAnnotations>
      <eParameters name="other" eType="#//IModelDescriptor"/>
    </eOperations>
    <eOperations name="isDescriptorFor" upperBound="-1" eType="#//EObjectToIModelDescriptorMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This operation checks whether the given element is described by this model descriptor.&#xD;&#xA;However, the check only includes the containment tree and optionally the elements' attributes, never their references!&#xD;&#xA;&#xD;&#xA;Just like applyStructure, the result is a map from all model elements within the containment tree of the given element to their respective model descriptors."/>
      </eAnnotations>
      <eParameters name="element" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="checkAttributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossReferences" upperBound="-1"
        eType="#//IElementReference" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns all cross-references for this model descriptors (and not for sub descriptors).&#xD;&#xA;Cross-references are those which refer to other model elements.&#xD;&#xA;Note that this does also include self references!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allCrossReferences" upperBound="-1"
        eType="#//IElementReference" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns all cross-references for this as well as for all subdescriptors.&#xD;&#xA;Cross-references are those which refer to other model elements.&#xD;&#xA;Note that this does also include self references!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selfReference" lowerBound="1"
        eType="#//IElementReference" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a symbolic reference to the element this particular model descriptor describes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allSelfReferences" lowerBound="1"
        upperBound="-1" eType="#//IElementReference" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the local self reference as well as the self references from all sub descriptors."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModelDescriptors" upperBound="-1"
        eType="#//IModelDescriptor" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns all sub descriptors of this model descriptors.&#xD;&#xA;It does not include nested model descriptors but only direct children!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptorUris" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The eclass of the element that is described."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeType">
    <eLiterals name="element"/>
    <eLiterals name="attribute" value="1"/>
    <eLiterals name="reference" value="2"/>
    <eLiterals name="group" value="3"/>
    <eLiterals name="unknown" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeKind">
    <eLiterals name="Addition"/>
    <eLiterals name="Deletion" value="1"/>
    <eLiterals name="Change" value="2"/>
    <eLiterals name="Move" value="3"/>
    <eLiterals name="Group" value="4"/>
    <eLiterals name="Unknown" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementReferenceToEObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//IElementReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectToIModelDescriptorMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IModelDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownChange" eSuperTypes="#//IndepChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDescriptorReference" eSuperTypes="#//IElementReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This implementation of symbolic references is only used for cross-references referring to added/deleted elements!"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvesTo" lowerBound="1"
        eType="#//IModelDescriptor"/>
  </eClassifiers>
</ecore:EPackage>
