/*
 * generated by Xtext
 */
package org.eclipse.emf.compare.epatch.dsl.parser.packrat;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.packrat.AbstractPackratParser;
import org.eclipse.xtext.parser.packrat.IParseResultFactory;
import org.eclipse.xtext.parser.packrat.AbstractParserConfiguration.IInternalParserConfiguration;

import org.eclipse.emf.compare.epatch.dsl.services.EpatchGrammarAccess;

public class EpatchPackratParser extends AbstractPackratParser {

	@Inject
	public EpatchPackratParser(IParseResultFactory parseResultFactory, EpatchGrammarAccess grammarAccess) {
		super(parseResultFactory, grammarAccess);
	}

	@Override
	protected org.eclipse.emf.compare.epatch.dsl.parser.packrat.EpatchParserConfiguration createParserConfiguration(
			IInternalParserConfiguration configuration) {
		return new org.eclipse.emf.compare.epatch.dsl.parser.packrat.EpatchParserConfiguration(configuration,
				getGrammarAccess());
	}

	@Override
	protected EpatchGrammarAccess getGrammarAccess() {
		return (EpatchGrammarAccess)super.getGrammarAccess();
	}

}
